-- Migration: tabela de links do site por marca + campo produto em lives

-- ── Tabela site_links ────────────────────────────────────────────
create table if not exists site_links (
  id         uuid primary key default gen_random_uuid(),
  brand      text not null,
  categoria  text not null,
  produto    text not null,
  link       text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table site_links enable row level security;
do $$ begin
  if not exists (
    select 1 from pg_policies where tablename = 'site_links' and policyname = 'allow all on site_links'
  ) then
    execute 'create policy "allow all on site_links" on site_links for all using (true) with check (true)';
  end if;
end $$;

create index if not exists idx_site_links_brand on site_links (brand);

-- ── Campo produto em lives (para beleza brands) ──────────────────
alter table lives add column if not exists produto text;

-- ── Seed: Links do Site - Gocase ─────────────────────────────────
insert into site_links (brand, categoria, produto, link) values
('gocase', '-',        'HOME',                        'https://www.gocase.com.br/'),
('gocase', 'case',     'Case',                        'https://www.gocase.com.br/capinha-para-celular'),
('gocase', 'case',     'CaseBold',                    'https://www.gocase.com.br/capinhas-boldmagsafe'),
('gocase', 'case',     'CaseDuo',                     'https://www.gocase.com.br/capinha-para-celular//?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&case_device=caseduopb-iphone14pro'),
('gocase', 'case',     'CaseFascino',                 'https://www.gocase.com.br/capinhas-fascino'),
('gocase', 'case',     'CaseInfinite',                'https://www.gocase.com.br/capinha-para-celular//?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&case_device=infiniteblack-iphone14pro'),
('gocase', 'coleção',  'UmCartao',                    'https://www.gocase.com.br/um-cartao'),
('gocase', 'térmicos', 'CopoDaily',                   'https://www.gocase.com.br/copodaily'),
('gocase', 'térmicos', 'CopoLife',                    'https://www.gocase.com.br/copo-life-lp'),
('gocase', 'térmicos', 'CopoTermico',                 'https://www.gocase.com.br/copotermico'),
('gocase', 'térmicos', 'GarrafaFlip',                 'https://www.gocase.com.br/garrafaflippro'),
('gocase', 'térmicos', 'GarrafaFresh',                'https://www.gocase.com.br/garrafatermica'),
('gocase', 'térmicos', 'GarrafaMagsafe',              'https://www.gocase.com.br/garrafamagsafe-lp'),
('gocase', 'térmicos', 'GarrafaMini',                 'https://www.gocase.com.br/garrafamini'),
('gocase', 'térmicos', 'GarrafaUrban',                'https://www.gocase.com.br/garrafaurban'),
('gocase', 'têxtil',   'BolsaJoy',                    'https://www.gocase.com.br/gobolsasjoy'),
('gocase', 'têxtil',   'LancheiraMixFruit',            'https://www.gocase.com.br/golancheiras'),
('gocase', 'têxtil',   'LancheiraUrban',               'https://www.gocase.com.br/bolsa-termica-urban'),
('gocase', 'têxtil',   'MalaTrip',                     'https://www.gocase.com.br/mala-de-bordo'),
('gocase', 'têxtil',   'ToteDaily',                    'https://www.gocase.com.br/gototedaily'),
('gocase', 'têxtil',   'ToteMini',                     'https://www.gocase.com.br/gototemini'),
('gocase', 'têxtil',   'TotePuffer',                   'https://www.gocase.com.br/tote-puffer'),
('gocase', 'térmicos', 'LinhaTermica',                 'https://www.gocase.com.br/linhatermica'),
('gocase', 'têxtil',   'BolsaMoove',                   'https://www.gocase.com.br/bolsamoove'),
('gocase', 'case',     'Florais',                      'https://www.gocase.com.br/capinha-para-celular//?sorting=newest&product_filter=capinha-para-celular&page=1&new=1&taxon=themes%2Fflorais'),
('gocase', 'têxtil',   'PETS',                         'https://www.gocase.com.br/linhapet'),
('gocase', '-',        'OUTLET',                       'https://www.gocase.com.br/outlet-2025'),
('gocase', 'case',     'CaseDisney',                   'https://www.gocase.com.br/capinha-para-celular//?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=colecoes%2Fdisney'),
('gocase', 'têxtil',   'NecessaireMake',               'https://www.gocase.com.br/necessaires'),
('gocase', 'case',     'CaseMinimalista',              'https://www.gocase.com.br/capinha-para-celular/?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=themes%2Fminimalist'),
('gocase', 'case',     'CaseMeuPet',                   'https://www.gocase.com.br/capinha-para-celular/?taxon=themes%2Fmy-pet&product_filter=capinha-para-celular&page=1&sorting=favorites&new=1'),
('gocase', 'têxtil',   'MochilaPop',                   'https://www.gocase.com.br/mochilas-pop'),
('gocase', 'têxtil',   'MakeupDoubleMelancia',         'https://www.gocase.com.br/necessaires/?case_device=necessairemelancia-makeupdouble&product_filter=necessaires&page=1&sorting=favorites&new=1'),
('gocase', 'têxtil',   'TermicaFruitRosa',             'https://www.gocase.com.br/bolsa-fruit/?case_device=fruitrosa-lancheirafruitbr&product_filter=bolsa-fruit&page=1&sorting=favorites&new=1'),
('gocase', 'térmicos', 'Minisemcanudo',                'https://www.gocase.com.br/garrafa-mini/?product_filter=garrafa-mini&page=1&sorting=favorites&new=1&case_device=360freshminipreta-garrafafresh350ebook'),
('gocase', 'têxtil',   'MochilaFun',                   'https://www.gocase.com.br/mochila-fun/?product_filter=mochila-fun&page=2&sorting=favorites&new=1'),
('gocase', 'case',     'CaseFloral',                   'https://www.gocase.com.br/capinha-para-celular//?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=themes%2Fflorais'),
('gocase', 'case',     'CaseCoquette',                 'https://www.gocase.com.br/capinha-para-celular/?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=themes%2Fcoquette'),
('gocase', 'têxtil',   'MakeupDoubleRosa',             'https://www.gocase.com.br/necessaires/?case_device=necessairerosa-makeupdouble&product_filter=necessaires&page=1&sorting=favorites&new=1'),
('gocase', 'têxtil',   'MochilaCasualPreta',           'https://www.gocase.com.br/mochila-notebook-casual'),
('gocase', 'têxtil',   'MakeupMagicalStitch',          'https://www.gocase.com.br/necessaires/?product_filter=necessaires&page=1&sorting=favorites&taxon=colecoes%2Fdisney%2Flilo-e-stitch&new=1'),
('gocase', 'têxtil',   'TermicaFunRose',               'https://www.gocase.com.br/bolsa-termica-fun/?product_filter=bolsa-termica-fun&page=1&sorting=favorites&new=1&case_device=lancheirarose-lancheirabts'),
('gocase', 'têxtil',   'TermicaMixCoracoesFlutuantes', 'https://www.gocase.com.br/mix-coracoes'),
('gocase', 'case',     'CaseReligiao',                 'https://www.gocase.com.br/capinha-para-celular//?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=themes%2Freligiao'),
('gocase', 'têxtil',   'CapaNotebookSlim',             'https://www.gocase.com.br/capa-para-notebook-slim'),
('gocase', 'têxtil',   'MakeupMapaMundiRosa',          'https://www.gocase.com.br/necessaires/?taxon=collections%2Ffull-print&product_filter=necessaires&page=1&sorting=favorites&new=1'),
('gocase', 'case',     'CaseGeek',                     'https://www.gocase.com.br/capinha-para-celular/?taxon=collections%2Fgeek&product_filter=capinha-para-celular&page=1&sorting=favorites&new=1'),
('gocase', 'case',     'CaseBookLover',                'https://www.gocase.com.br/capinha-para-celular//?taxon=collections%2Fbook-lover&product_filter=capinha-para-celular&page=1&sorting=favorites&new=1'),
('gocase', 'case',     'CaseHelloKitty',               'https://www.gocase.com.br/capinha-para-celular//?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=collections%2Fsanrio'),
('gocase', 'case',     'CaseProfissao',                'https://www.gocase.com.br/capinha-para-celular//?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=themes%2Fprofissoes'),
('gocase', 'têxtil',   'Gostrap',                      'https://www.gocase.com.br/cordao-de-cases/p'),
('gocase', 'case',     'CaseAndroid',                  'https://www.gocase.com.br/capinha-para-celular/?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&case_device=infiniteair-galaxya56'),
('gocase', 'case',     'CaseSignos',                   'https://www.gocase.com.br/capinha-para-celular//?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=themes%2Fmistico'),
('gocase', 'térmicos', 'GarrafaFun',                   'https://www.gocase.com.br/garrafafun'),
('gocase', 'têxtil',   'LancheiraFun',                 'https://www.gocase.com.br/bolsa-termica-fun/?product_filter=bolsa-termica-fun&page=1&sorting=favorites&new=1'),
('gocase', 'têxtil',   'MochilaVoyage',                'https://www.gocase.com.br/mochila-voyage'),
('gocase', 'têxtil',   'ToteShopper',                  'https://www.gocase.com.br/toteshopper'),
('gocase', 'coleção',  'MarciaSensitiva',              'https://www.gocase.com.br/marcia-sensitiva'),
('gocase', 'térmicos', 'TacaTermica',                  'https://www.gocase.com.br/taca-termica-drink'),
('gocase', 'coleção',  'Corinthians',                  'https://www.gocase.com.br/corinthians'),
('gocase', 'têxtil',   'EstojoFun',                    'https://www.gocase.com.br/estojo-fun/?product_filter=estojo-fun&page=1&sorting=favorites&new=1'),
('gocase', 'têxtil',   'MochilaRodinhasFun',           'https://www.gocase.com.br/mochila-carrinho-fun/'),
('gocase', 'têxtil',   'Malas',                        'https://www.gocase.com.br/malatrip'),
('gocase', 'case',     'CaseArmys',                    'https://www.gocase.com.br/capinha-para-celular//?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=collections%2Farmys-collection'),
('gocase', 'case',     'CaseHarryStyles',              'https://www.gocase.com.br/capinha-para-celular-disco-ball/p'),
('gocase', 'têxtil',   'LancheiraPlay',                'https://www.gocase.com.br/bolsa-termica-play'),
('gocase', 'coleção',  'ColecaoVerao',                 'https://www.gocase.com.br/colecao-verao-2026'),
('gocase', 'case',     'HeatedRivalry',                'https://www.gocase.com.br/capinha-para-celular-jersey-hoquei-hollanov/p'),
('gocase', 'case',     'MolhoBaiano',                  'https://www.gocase.com.br/capinha-para-celular-molho-baiano/p'),
('gocase', 'case',     'SwagBieber',                   'https://www.gocase.com.br/capinha-para-celular-swag/p'),
('gocase', 'case',     'HeyManAmen',                   'https://www.gocase.com.br/capinha-para-celular-hey-men-amen/p'),
('gocase', 'case',     'CadeiradeBar',                 'https://www.gocase.com.br/capinha-para-celular-cadeira-de-bar/p'),
('gocase', 'case',     'OceanEyes',                    'https://www.gocase.com.br/capinha-para-celular-ocean-eyes/p'),
('gocase', 'case',     'CaseVerao',                    'https://www.gocase.com.br/capinha-para-celular/?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&taxon=collections%2Fverao-2026'),
('gocase', 'têxtil',   'Mochilas',                     'https://www.gocase.com.br/mochilas-lp'),
('gocase', 'case',     'CaseOpalite',                  'https://www.gocase.com.br/capinha-para-celular-opalite-sky/p'),
('gocase', 'têxtil',   'BolsaVoyage',                  'https://www.gocase.com.br/bolsa-voyage'),
('gocase', 'têxtil',   'MalaBold',                     'https://www.gocase.com.br/mala-bold-lp'),
('gocase', 'térmicos', 'HomeGarrafas',                 'https://www.gocase.com.br/garrafatermica'),
('gocase', 'têxtil',   'HomeTotes',                    'https://www.gocase.com.br/gototes'),
('gocase', 'térmicos', 'HomeCopos',                    'https://www.gocase.com.br/copos'),
('gocase', 'têxtil',   'HomeBolsas',                   'https://www.gocase.com.br/joymoove'),
('gocase', 'case',     'CaseFlamengo',                 'https://www.gocase.com.br/flamengo-uniforme-1-2026-escudo/p'),
('gocase', 'case',     'CaseFortaleza',                'https://www.gocase.com.br/fortaleza-uniforme-2-2026-personalizado/p'),
('gocase', 'case',     'CaseGremio',                   'https://www.gocase.com.br/gremio-uniforme-1-2025/p'),
('gocase', 'case',     'CaseCruzeiro',                 'https://www.gocase.com.br/cruzeiro-uniforme-1-2026/p'),
('gocase', 'têxtil',   'CaseNotebook',                 'https://www.gocase.com.br/gonotebook'),
('gocase', 'têxtil',   'CaseNotebookPuffer',           'https://www.gocase.com.br/capa-notebook-puffer'),
('gocase', 'têxtil',   'NecessairePuffer',             'https://www.gocase.com.br/necessaires-puffer'),
('gocase', 'case',     'Iphone17e',                    'https://www.gocase.com.br/capinha-para-celular/?sorting=favorites&product_filter=capinha-para-celular&page=1&new=1&case_device=infiniteair-iphone17e'),
('gocase', 'coleção',  'ColecaoOutono',                'https://www.gocase.com.br/colecao-outono-2026'),
('gocase', 'têxtil',   'TotePop',                      'https://www.gocase.com.br/tote-pop'),
('gocase', 'coleção',  'ColecaoSotemnoBrasil',          'https://www.gocase.com.br/so-tem-no-brasil'),
('gocase', 'coleção',  'LinhaFitness',                  'https://www.gocase.com.br/linha-fitness-lp'),
('gocase', 'coleção',  'LinhaCare',                     'https://www.gocase.com.br/linha-care'),
('gocase', 'case',     'CaseCoracoesBordadosPedrarias', 'https://www.gocase.com.br/capinha-para-celular-coracoes-bordados-pedrarias/p'),
('gocase', 'case',     'CaseIniciaisCosmicas',          'https://www.gocase.com.br/capinha-para-celular-iniciais-cosmicas/p'),
('gocase', 'case',     'CaseFloresdoCampoAquarela',     'https://www.gocase.com.br/capinha-para-celular-flores-do-campo-em-aquarela/p'),
('gocase', 'case',     'CaseVichyColors',               'https://www.gocase.com.br/vichy-colors/p'),
('gocase', 'térmicos', 'AquiEBrasil',                   'https://www.gocase.com.br/colecao-cbf'),
('gocase', 'térmicos', 'DropCandy',                     'https://www.gocase.com.br/colecao-candy-colors'),
('gocase', 'coleção',  'Diadosnamorados',               'https://www.gocase.com.br/golovers-dia-dos-namorados'),
('gocase', 'coleção',  'GabiBrandt',                    'https://www.gocase.com.br/gabi-brandt'),
('gocase', 'estampa',  'InitialStar',                   'https://www.gocase.com.br/search?q=initial%20star&searchSkipSmartRedirect=true'),
('gocase', 'estampa',  'IconHeart',                     'https://www.gocase.com.br/search?q=icon%20heart&searchSkipSmartRedirect=true'),
('gocase', 'estampa',  'Girlboss',                      'https://www.gocase.com.br/search?q=girlboss&searchSkipSmartRedirect=true'),
('gocase', 'estampa',  'SportandFancy',                 'https://www.gocase.com.br/search?q=sport%20and%20fancy&searchSkipSmartRedirect=true'),
('gocase', 'estampa',  'Girlonthego',                   'https://www.gocase.com.br/search?q=girl%20on%20the%20go&searchSkipSmartRedirect=true'),
('gocase', 'coleção',  'Snoopy',                        'https://www.gocase.com.br/so-tem-no-brasil-termicos?taxon=collections%2Fsnoopy&product_filter=so-tem-no-brasil-termicos&page=1&sorting=favorites&new=1'),
('gocase', 'coleção',  'Disney',                        'https://www.gocase.com.br/so-tem-no-brasil-termicos?taxon=colecoes%2Fdisney&product_filter=so-tem-no-brasil-termicos&page=1&sorting=favorites&new=1'),
('gocase', 'têxtil',   'BolsaFitness',                  'https://www.gocase.com.br/bolsa-fitness-puffer/?q=0'),
('gocase', 'têxtil',   'Bolsagarrafa',                  'https://www.gocase.com.br/bolsa-garrafa'),
('gocase', 'têxtil',   'Totemoon',                      'https://www.gocase.com.br/tote-moon-puffer'),
('gocase', 'coleção',  'Pride',                         'https://www.gocase.com.br/gopride'),
('gocase', 'coleção',  'Houseofdragon',                 'https://www.gocase.com.br/search?q=house%20of%20dragon&searchSkipSmartRedirect=false&enableCatalogFacetsSearch=false'),
('gocase', 'case',     'Timesdefutebol',                'https://www.gocase.com.br/capinha-para-celular/?sorting=newest&product_filter=capinha-para-celular&page=2&new=1&taxon=collections%2Ftimes-de-futebol');

